[package]
name = "tldextract"
version = "0.1.0"
authors = ["Wu Young <doomsplayer@gmail.com>"]
description = "extract domain info from a url"
readme = "README.md"
documentation = "http://wooya.me/tldextract-rs/tldextract/index.html"
repository = "https://github.com/doomsplayer/tldextract-rs"
license = "MIT"
keywords = ["tld", "extract", "domain"]

[dependencies]
url = "^1.2"
error-chain = "^0.5"
idna = "0.1"
# serde = "^0.8"
serde_json = "^0.8"
# tokio-core = "^0.1"
# futures = "^0.1"
hyper = "^0.9"
regex = "^0.1"

[features]
default = ["BTreeSet"]
HashSet = []
BTreeSet = []
unstable = []