[package]
name = "tldextract"
version = "0.4.0"
authors = ["Young Wu <doomsplayer@gmail.com>"]
description = "extract domain info from a url"
readme = "README.md"
documentation = "http://wooya.me/tldextract-rs/tldextract/index.html"
repository = "https://github.com/doomsplayer/tldextract-rs"
license = "MIT"
keywords = ["tld", "extract", "domain"]

[dependencies]
url = "1.2"
error-chain = "0.9"
idna = "0.1"
serde_json = "0.9"
reqwest = "0.4"
regex = "0.2"

[features]
default = ["BTreeSet"]
HashSet = []
BTreeSet = []
unstable = []
