[package]
name = "tldextract"
version = "0.5.0"
authors = ["Young Wu <doomsplayer@gmail.com>"]
description = "extract domain info from a url"
readme = "README.md"
documentation = "http://wooya.me/tldextract-rs/tldextract/index.html"
repository = "https://github.com/doomsplayer/tldextract-rs"
license = "MIT"
keywords = ["tld", "extract", "domain"]

[dependencies]
url = "1"
error-chain = "0.11"
idna = "0.1"
serde_json = "1"
reqwest = "0.8"
regex = "0.2"
log = "0.3"

[dev-dependencies]
env_logger = "0.4"

[features]
default = ["BTreeSet"]
HashSet = []
BTreeSet = []
unstable = []
